
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘11.0’
use_frameworks!
target 'EPJH' do

    pod 'MJRefresh' , '3.1.15.7'
    pod 'MJExtension', '3.0.15.1'
    pod 'SDWebImage', '4.4.6'
    pod 'AFNetworking', '3.2.1'
    pod 'MBProgressHUD', '0.9.2'
    pod 'SDCycleScrollView', '1.75'
    pod 'IQKeyboardManager', '6.2.0'

    pod 'FMDB'   , '2.7.2'
    pod 'YYKit'  , '1.0.9'
    pod 'Masonry' , '1.1.0'

    pod 'UMCCommon'
    pod 'UMCShare/UI'
    pod 'UMCSecurityPlugins'
    pod 'UMCShare/Social/ReducedQQ'
    pod 'UMCShare/Social/ReducedWeChat'

    pod 'WechatOpenSDK' , '1.8.2'
    pod 'TencentOpenAPI-Unofficial', '~> 3.3.0'

    pod 'Bugly', '2.5.0'
    pod 'SSZipArchive'  #zip解压缩
    pod 'BRPickerView'  #各种选择器
    
end
